// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace CarameliPad
{
	public partial class PagingController : UIViewController
	{
		public PagingController (IntPtr handle) : base (handle)
		{
		}
	}
}
